obj-$(CONFIG_SHSYS_CUST) += sh_sleeptest.o
obj-$(CONFIG_SHSYS_CUST) += sh_smem.o
obj-$(CONFIG_SHSYS_CUST) += sh_smem_read.o
obj-$(CONFIG_SHSYS_CUST) += sh_systime.o
obj-$(CONFIG_ANDROID_ENGINEERING) += sh_regaxs.o
obj-$(CONFIG_ANDROID_ENGINEERING) += sh_gpio.o
