#
# Makefile for the FeliCa/NFC drivers.
#
# felica
obj-$(CONFIG_SHFELICA) += felica.o
obj-$(CONFIG_SHFELICA) += mfcuart.o
obj-$(CONFIG_SHFELICA) += mvdd.o
obj-$(CONFIG_SHFELICA) += clf.o

# snfc
obj-$(CONFIG_SHSNFC) += snfc.o
obj-$(CONFIG_SHSNFC) += clf.o

# broadcom
obj-$(CONFIG_BCM2079X) += clf.o

