obj-$(CONFIG_REGMAP) += regmap.o regcache.o
obj-$(CONFIG_REGMAP) += regcache-rbtree.o regcache-lzo.o
obj-$(CONFIG_DEBUG_FS) += regmap-debugfs.o
obj-$(CONFIG_REGMAP_I2C) += regmap-i2c.o
obj-$(CONFIG_REGMAP_SPI) += regmap-spi.o
obj-$(CONFIG_REGMAP_IRQ) += regmap-irq.o
#CONFIG_SH_AUDIO_DRIVER-> 03-001
obj-$(CONFIG_REGMAP_SLIMBUS) += regmap-slimbus.o
#CONFIG_SH_AUDIO_DRIVER<- 03-001