# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_FSA8008) += hds_fsa8008.o
#CONFIG_SH_AUDIO_DRIVER-> 03-001
obj-$(CONFIG_SWITCH_ARIZONA)	+= switch-arizona.o
#CONFIG_SH_AUDIO_DRIVER<- 03-001

